version: "3.8"

services:
  backend:
    image: pranavreddy123/fastapi-backend:latest
    container_name: analytics_backend
    ports:
      - "4000:4000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}  
    restart: always

  frontend:
    image: pranavreddy123/streamlit-frontend:latest
    container_name: analytics_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always
