version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY} 
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend 
    restart: always

networks:
  default:
    driver: bridge
